### ISSUE TITLE
++doc request

### ISSUE THREAD

**Issue by jordila** [Oweoqi/twister_script#1]
Hey, first of all thanks for... !
I was looking for a simple way to install Twister on Debian... Seems that i've got to the right place.
Mmhh... but, could you extend a little bit more on the _how to_ ?
thanks

**Comment by Oweoqi** [comment]
Hey :) I hope this helps https://github.com/Oweoqi/twister_script/wiki

**Comment by jordila** [comment]
Crystal clear :-)
See you in twister ...
